[package]
name = "intersection_filter"
authors = ["Yang Chen <matthiasychen@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.23.0"
embree = { path = "../.." }
support = { path = "../support" }
