[package]
name = "dynamic_scene"
version = "0.1.0"
authors = ["Yang Chen <matthiasychen@gmail.com>"]
edition = "2021"

[dependencies]
glam = "0.22.0"
embree = { path = "../.." }
support = { path = "../support" }

