[package]
name = "triangle"
version = "0.1.0"
authors = ["Will Usher <will@willusher.io>"]
edition = "2021"

[dependencies]
embree = { path = "../../" }
support = { path = "../support" }
cgmath = "0.18"

