[package]
name = "triangle_geometry"
version = "0.1.0"
authors = ["Will Usher <will@willusher.io>"]
edition = "2021"

[dependencies]
glam = "0.22.0"
embree = { path = "../.." }
support = { path = "../support" }
rayon = "1.5"

